# -*- coding: utf-8 -*-
"""amazon_sale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glgZRCoyy7N4E0UA1txbv-1YJ21rGjQZ
"""

import pandas as pd
df=pd.read_csv("/Amazon Sale Report.csv")

print(df.head())
print(df.info())

df=df.drop(columns=["Unnamed: 22"],errors='ignore')

df.columns=df.columns.str.strip().str.lower().str.replace("-","_")

df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['qty'] = pd.to_numeric(df['qty'], errors='coerce')

print(df.head())

df['ship_postal_code'] = df['ship_postal_code'].astype(str).str.replace('.0', '', regex=False)
df['status'] = df['status'].str.strip().str.lower()
df['category'] = df['category'].str.strip().str.lower()
df['ship_state'] = df['ship_state'].str.strip().str.title()

print(df.isnull().sum())

df['courier_status'] = df['courier_status'].fillna("unknown")
df['promotion_ids'] = df['promotion_ids'].fillna("no_promo")

df = df.dropna(subset=['amount', 'date'])

df = df.drop_duplicates()

df['month'] = df['date'].dt.to_period('M')

df['revenue'] = df['amount'] * df['qty']

df.to_csv("cleaned_amazon_data.csv", index=False)
